version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wsr
    ports:
      - "3307:3306"
    volumes:
      - "./DDL.sql:/docker-entrypoint-initdb.d/1.sql"

  lab18:
    image: swatar/lab18
    build: .
    container_name: "lab18"
    depends_on:
      - db
    ports:
      - "8080:8080"